//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCCL_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FCCLEntities : DbContext
    {
        public FCCLEntities()
            : base("name=FCCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Interval> Intervals { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual ObjectResult<sp_Get_RegistruRegeptie_Result> sp_Get_RegistruRegeptie(Nullable<System.DateTime> testDate)
        {
            var testDateParameter = testDate.HasValue ?
                new ObjectParameter("TestDate", testDate) :
                new ObjectParameter("TestDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_RegistruRegeptie_Result>("sp_Get_RegistruRegeptie", testDateParameter);
        }
    
        public virtual ObjectResult<sp_Get_Users_Result> sp_Get_Users(string userName = null)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Users_Result>("sp_Get_Users", userNameParameter);
        }
    }
}
