//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCCL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public short Type { get; set; }
        public string Description { get; set; }
        public decimal MinVal { get; set; }
        public decimal MaxVal { get; set; }
        public short Application { get; set; }
    }
}
