//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCCL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public long OrderNumber { get; set; }
        public string FullOrderNumber { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public System.DateTime SampleDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public bool Imported { get; set; }
        public Nullable<int> AnalyzedSampleCount { get; set; }
        public Nullable<int> SampleCount { get; set; }
        public Nullable<short> Application { get; set; }
    }
}
